POST http://localhost:5077/items
Content-Type: application/json

{
    "name": "oatmeal",
    "quantity": "3",
    "unit": "cups",
    "expDate": "2023-06-01",
    "location": "pantry",
    "startDateTime": "2023-05-01T08:00:00",
    "endDateTime": "2023-05-01T11:00:00"
}